# Generated by Django 2.2.17 on 2021-01-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumkiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('old_price', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('article', models.CharField(max_length=20)),
                ('descrip', models.TextField()),
                ('descripoint', models.TextField()),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='images')),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sumkiapp.Category')),
                ('product_collection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sumkiapp.Collection')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
