# Generated by Django 2.2.17 on 2021-01-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumkiapp', '0004_auto_20210111_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_collection',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
