# Generated by Django 2.2.17 on 2021-01-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumkiapp', '0005_auto_20210111_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
