# Generated by Django 2.2.17 on 2021-01-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumkiapp', '0007_auto_20210114_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Products'},
        ),
    ]
