# Generated by Django 2.2.17 on 2021-01-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumkiapp', '0008_auto_20210115_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name_plural': 'Products'},
        ),
    ]
