# Generated by Django 2.2.17 on 2021-01-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumkiapp', '0010_auto_20210116_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickorder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
