# Generated by Django 2.2.17 on 2021-07-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumkiapp', '0017_auto_20210721_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descripoint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
