# Generated by Django 2.2.17 on 2022-09-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumkiapp', '0019_auto_20220922_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='primary_image',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='sumkiapp.ProductImage'),
        ),
    ]
